### ISSUE TITLE
Use `containers/` dir instead of `XContainer.js`

### ISSUE THREAD

**Issue by karlhorky** [whosmysanta/whosmysanta#3]

**Comment by karlhorky** [comment]
We may want to reconsider using separation for the containers at all, since colocation of queries and views is a pattern with Relay:

https://facebook.github.io/relay/

> COLOCATION
> Queries live next to the views that rely on them, so you can easily reason about your app.

**Comment by glennreyes** [comment]
Let's leave this for now and let's use `/components` for every React components to keep the project as simple as possible
