### ISSUE TITLE
Set up data persistence (BaaS? database?)

### ISSUE THREAD

**Issue by karlhorky** [whosmysanta/whosmysanta#4]
GraphQL BaaSes (Backends as a Service) are available, from most to least expensive:

https://graph.cool/
https://www.reindex.io/
https://scaphold.io/

---

Or non-GraphQL realtime BaaSes:
https://firebase.google.com/
https://horizon.io/

We probably don't need realtime though, and they are not as nicely integrated into the ecosystem.

**Comment by glennreyes** [comment]
GaaS scaphold looks real good for this purpose!

**Comment by glennreyes** [comment]
We'll use MongoDB for now and reconsider it once we've launched an MVP
