### ISSUE TITLE
Notify invitees when a group is being created

### ISSUE THREAD

**Issue by glennreyes** [whosmysanta/whosmysanta#7]
Let's notify every invitee about the santa group when it is being created by default.

For that we need an appropriate mail provider:

* https://www.mailgun.com/ (cheapest)
* https://aws.amazon.com/ses (cheap when using EC2)
* https://sendgrid.com/
* https://www.mailjet.com/

Alternatively the group creator should have the option to send the _group URL_ to each invitee by hand (eg. per text message or WhatsApp).

**Comment by karlhorky** [comment]
Working with Mailgun!
